version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=prod
      - PORT=8080
      - DB_URL=mongodb://admin:MongoDB02@mongo:27017/my-employees?authSource=admin
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=MongoDB02
      - MONGO_INITDB_DATABASE=my-employees
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge